language: generic
sudo: required    // hey Travis we need super user level access to execute this build 
services:
  - docker        // travis will install docker in the container

before_install:
  - docker build -f Dockerfile -t my-springboot-app . 

deploy:
  provider: elasticbeanstalk
  region:  us-east-2        
  app: "first-test-docker-app"      
  env: "Firsttestdockerapp-env"  
  bucket_name: "elasticbeanstalk-us-east-2-383486092839"     
  bucket_path: "first-test-docker-app"     
  on: 
    branch: master            
  access_key_id: $awsk
  secret_access_key: $awsp